# Build settings
# Gems
gems:
- jekyll-paginate
- jekyll-feed
- jekyll-sitemap

# url is the full website URL
# baseurl is the website's URL without the hostname
# If you are hosting it on Github for some project with name 'projectname', then the url and baseurl should look like:
#url: "http://username.github.io/projectname"
#baseurl: "/projectname"
url: "https://bchetty.com"
enforce_ssl: bchetty.com
baseurl: ""

# Title of website
title: Babji Chetty

#Default keywords (used if no keywords are specified on a page basis)
keywords: test1, test2, etc

# Short description of your site
desc: Babji, Chetty

# --- Navigation bar options --- #

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "/assets/img/bchetty_rounded1.png"

# List of links in the navigation bar
nav-links:
  Home: ""
  Blog: "blog"
  Travel: "travel"
  Photos: "photos"
  About Me: "aboutme"
  Archive: "archive"
  Contact: "contact"

# --- Footer options --- #

# If the values are empty, they are ignored
profile:
  name: Babji Chetty
  email: ""
  facebook: yourname
  github: bchetty
  twitter: chettyb
  linkedin: in/prashanthchetty
  stackoverflow: 401727/bchetty

config:
  fb-enabled: false
  email-enabled: false
  github-enabled: true
  twitter-enabled: true
  linkedin-enabled: true
  stackoverflow-enabled: true
  feed-enabled: true

# To display link in the footer section
pretty-url: "bchetty.com"

# --- Misc --- #

# Your Disqus profile (shortname) settings
disqus: "bchetty"

# Google Analytics Settings
google_analytics: "UA-74990483-1"

# Set these options as you need (For more information, check Jekyll's site)
timezone: "Europe/Berlin"
markdown: kramdown
#highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: /blog/:title
paginate: 5
paginate_path: blog/page:num/

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true  # add comments to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "default"
      show-avatar: true

# Exclude these files from production site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

created-by: Babji, Chetty
creator-url: https://bchetty.com
